hsr_admin/urls.py
from django.urls import path
from . import views

app_name = "hsr_admin"
urlpatterns = [
    path("", views.index, name="index"),
    path("logout/", views.user_logout, name="logout"),

    path("home/", views.home, name="home"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/new/", views.new_category, name="new_category"),
    path("categories/<int:pk>/", views.view_category, name="view_category"),

    path("rooms/", views.room_list, name="room_list"),
    path("rooms/<int:pk>/", views.view_room, name="view_room"),

    path("reservations/", views.reservation_list, name="reservation_list"),
    path("reservations/new/", views.new_reservation, name="new_reservation"),
    path("reservations/check/", views.check_availability, name="check_availability"),
    path(
        "reservations/<int:pk>/delete/",
        views.delete_reservation,
        name="delete_reservation",
    ),
    path("reservations/<int:pk>/", views.view_reservation, name="view_reservation"),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .api import router
from hsr_admin import urls
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin_main/", admin.site.urls),
        path("api/", include(router.urls)),
        path("app/", TemplateView.as_view(template_name="hsr_admin/app_index.html"), name="app"),
        path("app", TemplateView.as_view(template_name="hsr_admin/app_index.html"), name="app"),
        path("admin/", include(urls), name="hsr_admin"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static("/", document_root=settings.STATIC_ROOT)
)

hsr_admin/models.py
from django.db import models

# Create your models here.

hsr_admin/forms.py
from django import forms
from management.models import Reservation, RoomCategory


class LoginForm(forms.Form):
    email_address = forms.EmailField()
    password = forms.CharField()


class ReservationForm(forms.ModelForm):
    """Form definition for Reservaton."""

    class Meta:
        """Meta definition for Reservatonform."""

        model = Reservation
        fields = "__all__"


class CheckAvailabilityForm(forms.Form):
    arrival_date = forms.DateField()
    arrival_time = forms.TimeField()

    departure_date = forms.DateField()
    departure_time = forms.TimeField()


class CustomerForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email_address = forms.EmailField()
    phone_number = forms.CharField()
    identification_type = forms.CharField()
    identification_number = forms.CharField()
    


class BookingForm(forms.Form):
    room = forms.IntegerField()


class CategoryForm(forms.ModelForm):
    class Meta:
        model = RoomCategory
        fields = "__all__"

class RoomFilterForm(forms.Form):
    start_date = forms.DateField()
    start_time = forms.TimeField()
    end_date = forms.DateField()
    end_time = forms.TimeField()
    
class RoomUpdateForm(forms.Form):
    room_number = forms.CharField()
    description = forms.CharField()
    category = forms.ModelChoiceField(RoomCategory.objects.all())

class CategoryUpdateForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField()
    price = forms.FloatField()

hsr_admin/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.db.models import Q, F
from django.db import transaction
from django.utils.dateparse import parse_datetime
from django.utils.datetime_safe import datetime

from management.models import RoomCategory, Room, Customer, Reservation
from management.managers import RoomManager

from .forms import (
    BookingForm,
    CategoryUpdateForm,
    CheckAvailabilityForm,
    CustomerForm,
    LoginForm,
    ReservationForm,
    CategoryForm,
    RoomFilterForm,
    RoomUpdateForm,
)

# Create your views here.


def new_reservations():
    return Reservation.objects.filter(viewed=False).count()


def context_parse(context):
    context["status__"] = new_reservations()
    context["status__category"] = RoomCategory.objects.all().count()
    context["status__room"] = Room.objects.all().count()

    return context


def index(request: HttpRequest):
    if request.method.upper() == "POST":
        form = LoginForm(request.POST)

        if not form.is_valid():
            return render(
                request,
                template_name="hsr_admin/index.html",
                context={
                    "message": "Please provide a valid email address and password"
                },
            )

        try:
            data = form.cleaned_data
            user = User.objects.get(
                Q(email=data["email_address"]) | Q(username=data["email_address"])
            )
            if user.check_password(data["password"]):
                login(request, user)
                return redirect("hsr_admin:home")
        except User.DoesNotExist:
            pass

        return render(
            request,
            template_name="hsr_admin/index.html",
            context={"message": "Wrong email address or password"},
        )

    if request.user.is_authenticated:
        return redirect("hsr_admin:home")

    return render(request, template_name="hsr_admin/index.html")


def user_logout(request: HttpRequest):
    if request.user.is_authenticated:
        logout(request)

    return redirect("hsr_admin:index")


def home(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect("hsr_admin:index")
    return render(
        request, template_name="hsr_admin/dashboard.html", context=context_parse({})
    )


def category_list(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect(index)

    _categories = RoomCategory.objects.all()
    return render(
        request,
        template_name="hsr_admin/categories.html",
        context=context_parse({"categories": _categories}),
    )


def new_category(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect(index)

    if request.method == "GET":
        return render(request, "hsr_admin/new_category.html", context=context_parse({}))

    form = CategoryForm(request.POST, request.FILES)

    if not form.is_valid():
        return render(
            request,
            "hsr_admin/new_category.html",
            context=context_parse(
                {"message": "Please provide all the fields", "form": request.POST}
            ),
        )
    category = form.save()

    rooms = request.POST.get("rooms")

    if rooms:
        try:
            rooms = int(rooms)
            for i in range(rooms):
                room = Room(category=category)
                room.save()
        except Exception as e:
            pass

    return redirect("hsr_admin:category_list")


def reservation_list(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect(index)

    reservations = Reservation.objects.filter(viewed=True).order_by("-id")
    new_reservations = Reservation.objects.filter(viewed=False).order_by("-id")

    return render(
        request,
        "hsr_admin/reservation_list.html",
        context_parse(
            {"reservations": reservations, "new_reservations": new_reservations}
        ),
    )


def room_list(request: HttpRequest):
    if not request.user.is_authenticated:
        return redirect(index)

    form = RoomFilterForm(request.GET)

    if form.is_valid():
        data = form.cleaned_data
        start_date = parse_datetime(f"{data['start_date']} {data['start_time']}")
        end_date = parse_datetime(f"{data['end_date']} {data['end_time']}")

        rooms = RoomManager.taken_rooms(start_date=start_date, end_date=end_date)
    else:
        rooms = Room.objects.all()

    categories = RoomCategory.objects.all()

    colors = [
        "bg-red-700",
        "bg-indigo-700",
        "bg-green-700",
        "bg-purple-700",
        "bg-pink-700",
        "bg-violet-900",
        "bg-brown-700",
        "bg-slate-900",
    ]
    _colors = {}

    for cat in categories:
        _colors[cat.pk] = colors[cat.pk % len(categories)]

    return render(
        request,
        "hsr_admin/rooms.html",
        context_parse(
            {
                "categories": categories,
                "rooms": rooms,
                "colors": _colors,
                "form": request.GET,
            }
        ),
    )


def view_room(request: HttpRequest, pk):
    if not request.user.is_authenticated:
        return redirect(index)

    try:
        room = Room.objects.get(pk=pk)
        categories = RoomCategory.objects.all()

        if request.method == "POST":
            form = RoomUpdateForm(request.POST)
            if not form.is_valid():
                return render(
                    request,
                    "hsr_admin/view_room.html",
                    context_parse(
                        {
                            "room": room,
                            "reservations": room.reservations.all(),
                            "categories": categories,
                            "error": "Please provide all field",
                        }
                    ),
                )

            data = form.data

            room.category = categories.get(pk=int(data.get("category")))
            room.number = data.get("room_number")
            room.description = data.get("description")

            room.save()

            return render(
                request,
                "hsr_admin/view_room.html",
                context_parse(
                    {
                        "room": room,
                        "reservations": room.reservations.all(),
                        "categories": categories,
                        "success": "Room detail Updated",
                    }
                ),
            )

        return render(
            request,
            "hsr_admin/view_room.html",
            context_parse(
                {
                    "room": room,
                    "reservations": room.reservations.all(),
                    "categories": categories,
                }
            ),
        )
    except Room.DoesNotExist:
        return redirect("hsr_admin:room_list")


def view_category(request: HttpRequest, pk):
    if not request.user.is_authenticated:
        return redirect(index)

    try:
        category = RoomCategory.objects.get(pk=pk)

        if request.method == "POST":
            if request.POST["put"]:
                count = request.POST["count"]

                try:
                    count = int(count)
                    for i in range(count):
                        room = Room(category=category, number=Room.objects.count() + 1)

                        room.save()

                except Exception as e:
                    print(e)

                return redirect("hsr_admin:view_category", pk=category.pk)

            form = CategoryUpdateForm(request.POST)
            if not form.is_valid():
                return render(
                    request,
                    "hsr_admin/view_category.html",
                    context_parse(
                        {
                            "rooms": category.rooms.all(),
                            "category": category,
                            "error": "Please provide all field",
                        }
                    ),
                )

            data = form.cleaned_data

            category.title = data.get("title")
            category.description = data.get("description")
            category.price = data.get("price")
            category.save()

            return render(
                request,
                "hsr_admin/view_category.html",
                context_parse(
                    {
                        "rooms": category.rooms.all(),
                        "category": category,
                        "success": "CAtegory detail Updated",
                    }
                ),
            )
        elif request.method == "PUT":
            print(request.body)

        return render(
            request,
            "hsr_admin/view_category.html",
            context_parse(
                {
                    "rooms": category.rooms.all(),
                    "category": category,
                }
            ),
        )
    except Room.DoesNotExist:
        return redirect("hsr_admin:category_list")


def delete_reservation(request, pk):
    if not request.user.is_authenticated:
        return redirect(index)

    reservation = Reservation.objects.get(pk=pk)

    reservation.viewed = True
    reservation.save()

    if request.method == "POST":
        reservation.delete()
        return redirect("hsr_admin:reservation_list")

    return render(
        request,
        "hsr_admin/delete_reservation.html",
        context_parse({"reservation": reservation}),
    )


def view_reservation(request, pk):
    if not request.user.is_authenticated:
        return redirect(index)

    try:

hsr_admin/templates/hsr_admin/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} Star Exclusive Admin {% endblock title %}</title>

    
    <body class= "overflow-x-hidden bg-gray-800 text-white w-screen h-screen grid grid-cols-[64px,1fr] lg:grid-cols-[16rem,1fr] grid-rows-[64px,1fr]" >
        
        <div class=" col-start-1 col-end-3 shadow-md shadow-slate-400/5">
            <div class="h-full w-full items-center space-x-4 px-4 flex bg-gray-800 text-white p-4">
                <div class="flex-shrink-0">
                  <!-- Logo or application icon -->
                  <!-- <img src="logo.png" alt="Logo" class="h-8 w-8"> -->
                  <div class="h-8 w-9 flex items-center justify-center font-extrabold text-slate-400">
                    Star
                  </div>
                </div>
                <span class="text-xl !mr-auto">Star Exclusive</span>

                {% block actions %}
                    
                  {% endblock actions %}
                <div class="mx-6">
                  <!-- Navigation links -->
                  <a href="{% url 'hsr_admin:home' %}
" class="bg-gray-500 hover:bg-indigo-600 text-white font-
bold py-2 px-4 rounded ml-2">                                              HOME
                  </a>
                </div>
                <div class="flex-shrink-0">
                  
                  <a href="{% url 'hsr_admin:logout' %}" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded ml-2">
                    Logout
                  </a>
                </div>
              </div>
              
        </div>
    
        <div class="flex flex-col bg-gray-800 overflow-x-hidden shadow-md shadow-white/5">
            <div class="p-4 my-1 bg-gray-800 text-white text-sm font-semibold">Menu</div>
            <ul class="flex-grow">
              <li>
                <a href="{% url 'hsr_admin:category_list' %}" class="block p-4 hover:bg-gray-900">Room Category</a>
              </li>
              <li>
                <a href="{% url 'hsr_admin:room_list' %}" class="block p-4 hover:bg-gray-900">Rooms</a>
              </li>
              <li>
                <a href="{% url 'hsr_admin:reservation_list' %}" class="flex space-x-4 items-center p-4 hover:bg-gray-900">
                  <span>Reservation</span>
                  <div class="py-2 px-8 bg-indigo-500 text-white rounded-lg"> {{status__}} new</div>
                </a>
              </li>
              <li class="hidden">
                <a href="#" class="block p-4 hover:bg-gray-900">Customers</a>
              </li>
            </ul>
            <div class="mt-auto p-4">
              <a href="{% url 'hsr_admin:logout' %}" class="flex items-center justify-center text-center w-full bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded">
                <span>Logout</span>
              </a>
            </div>
          </div>
          
    
        <div class="col-start-2 row-start-2 overflow-y-auto">
            
            {% block body %}
                
            {% endblock body %}
                
        </div>
            
    </body>
        
  </head>
  <body></body>
</html>

hsr_admin/templates/hsr_admin/category.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>

<body>

</body>

</html>

hsr_admin/templates/hsr_admin/new_reservation.html
{% extends 'hsr_admin/base.html' %} {% block body %}
{% load static %}
<div class="text-center py-8">
  <span class="text-red-600">{{message}}</span>
</div>

{% if adding %}
<form method="POST" action="{% url 'hsr_admin:new_reservation' %}">
  {% csrf_token %} {% include 'hsr_admin/reservation_date_form.html' %}

  
  {% comment %}
  <div class="flex flex-col lg:flex-row justify-center lg:space-x-4 my-4 px-16">
    <div class="flex flex-col w-full">
      <label for="">Room Category</label>
      <select
        min="12/12/2023"
        class="bg-transparent border-white w-full shadow-md px-8 py-4 outline-none border-2 border-black/40 rounded-md hover:border-indigo-600"
        type="email"
        name="email_address"
      >
        
        {% for category in categories %}
        <option class="bg-slate-800 p-4 block" value="{{category.pk}}">
          {{category.title }} ({{category.price}})
        </option>
        {% endfor %}
          
        
      </select>
    </div>
  </div>
  {% endcomment %}
    

  <div class="flex flex-wrap px-4 lg:px-16 mt-16 space-x-8">
    
    {% for category in categories %}
    <div class="flex flex-row space-x-2 items-center shrink-0">
      <div class="h-10 aspect-square {{colors|get:category.pk}}"></div>
      <div class="flex flex-col">
        <span>{{category.title }} </span>
        <span>N {{category.price }} </span>
      </div>
    </div>
    {% endfor %}
      
  </div>
  <input type="room" hidden name="room" id="room">
  <div class="pt-16 px-4 lg:px-16 grid grid-cols-3 md:grid-cols-5 lg:grid-cols-12 gap-4 ">
    {% for room in rooms %}
      <div room-id = "{{room.id}}" room-category="{{room.category.id}}" class="room_item w-full {{colors|get:room.category.pk}} rounded-md">
        <div class=" relative overflow-hidden w-full aspect-square flex items-end justify-center py-4 px-1 rounded-md">
          <img src="{{room.category.cover.url}}" class="absolute top-0 left-0 h-full w-full object-cover" alt="">
          
        </div>
        <span class="block p-2">{{room}}</span>
      </div>
    {% endfor %}
      

  </div>

  <script>

    (function(){
      const roomInput = document.getElementById("room")
      const rooms = document.querySelectorAll(".room_item")

      rooms.forEach(room => {
        room.addEventListener("click", ()=>{
          let id = room.getAttribute("room-id")
          roomInput.value = id

          let pre = document.querySelector(".room_item.selected")
          if(pre)pre.classList.remove("border" ,"boreder-slate-500" ,"border-4","selected")

          room.classList.add("border" ,"boreder-slate-500" ,"border-4","selected")

        })
      });
    })()

  </script>

  <span class="text-2xl mt-16 block ml-16">Customer/Guest Information</span>

  {% include 'hsr_admin/guest_form.html' %}
  <div class="mr-auto my-6 px-4 lg:px-16">
    <button
      type="submit"
      class="px-4 py-4 bg-indigo-500 text-white rounded hover:bg-indigo-700 duration-300"
    >
      Make Reservation
    </button>
  </div>
</form>

{% else %}

<form method="POST" action="{% url 'hsr_admin:check_availability' %}">
  {% csrf_token %} {% include 'hsr_admin/reservation_date_form.html' %}

  <div class="mr-auto my-6 px-16">
    <button
      type="submit"
      class="px-4 py-4 bg-indigo-500 text-white rounded hover:bg-indigo-700 duration-300"
    >
      Check Room Avialable
    </button>
  </div>
</form>

{% endif %} {% endblock body %}

hsr_admin/templates/hsr_admin/reservation_list.html
{% extends 'hsr_admin/base.html' %}



{% block actions %}
<div class="flex space-x-2 px-4">
  <input type="text" placeholder="Reservation Code"
    class="w-64 py-2 px-4 border text-slate-900 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent">
  <a href="{%url 'hsr_admin:new_category'%}"
    class="bg-indigo-500 hover:bg-indigo-600 text-white font-semibold py-2 px-4 rounded">
    Search
  </a>
</div>
{% endblock actions %}


{% block title  %}
  Reservation List
{% endblock title  %}
  


{% block body %}

<div class="p-4">
<div class="flex space-x-4 mb-8">
  
  <h1 class="text-3xl p-4">Reservation List</h1>
  <a href="{% url 'hsr_admin:check_availability'%}"
    class="px-4 py-2 inline-block my-auto bg-blue-500 text-white rounded hover:bg-blue-700">New Reservation</a>

</div>
  <table class="min-w-full">
    <thead class="">
      <tr class="py-8">
        <th class="py-4 px-4  text-left">ID</th>
        <th class="py-4 px-4  text-left">Arrival Date</th>
        <th class="py-4 px-4  text-left">Departure Date</th>
        <th class="py-4 px-4  text-left">Customer</th>
        <th class="py-4 px-4  text-left">Room</th>
        <th class="py-4 px-4  text-left">Paid</th>


        <th class="py-4 px-4  text-left">Actions</th>
      </tr>
    </thead>
    <tbody>

      {% for reservation in new_reservations %}
      <tr>
        <td class="py-6 px-4 flex items-center space-x-2 text-left">


          <span>{{ reservation.code }}</span>
          {% if not reservation.viewed %}
          <div class="p-2 px-4 bg-indigo-400 rounded-sm">new </div>
          {% endif %}

        </td>
        <td class="py-6 px-4  text-left">{{ reservation.arrival_date.date }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.departure_date.date }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.customer.first_name }} {{ reservation.customer.last_name }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.room.number }} ({{reservation.room.category}})</td>
        <td class="py-6 px-4  text-left ">

          <div class="flex space-x-2">
            {% if reservation.paid %}
          <div class="h-6 aspect-square bg-teal-500 rounded-full">
          </div>
          {% else %}
          <div class="h-6 aspect-square bg-slate-500">
          </div>
          {% endif %}
          <span>{{reservation.room.category.price}}</span>
          </div>
        </td>

        <td class="py-2 px-4 flex space-x-2 text-left">
          <a href="{% url 'hsr_admin:view_reservation' reservation.id %}"
            class="block p-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 ">View</a>
          <a href="{% url 'hsr_admin:delete_reservation' reservation.id %}"
            class="block p-4 py-2 rounded-md bg-orange-500 hover:bg-orange-700">Cancel</a>
        </td>
      </tr>

      {% endfor %}

      {% for reservation in reservations %}
      <tr>
        <td class="py-6 px-4 flex items-center space-x-2 text-left">


          <span>{{ reservation.code }}</span>
          {% if not reservation.viewed %}
          <div class="p-2 px-4 bg-indigo-400 rounded-sm">new </div>
          {% endif %}

        </td>
        <td class="py-6 px-4  text-left">{{ reservation.arrival_date.date }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.departure_date.date }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.customer.first_name }} {{ reservation.customer.last_name }}</td>
        <td class="py-6 px-4  text-left">{{ reservation.room.number }} ({{reservation.room.category}})</td>

        <td class="py-6 px-4  text-left ">

          <div class="flex space-x-2">
            {% if reservation.paid %}
          <div class="h-6 aspect-square bg-teal-500 rounded-full">
          </div>
          {% else %}
          <div class="h-6 aspect-square bg-slate-500">
          </div>
          {% endif %}
          <span>{{reservation.room.category.price}}</span>
          </div>
        </td>

        <td class="py-2 px-4 flex space-x-2 text-left">
          <a href="{% url 'hsr_admin:view_reservation' reservation.id %}"
            class="block p-4 py-2 rounded-md bg-blue-500 hover:bg-blue-700 ">View</a>
          <!-- <a href="{% url 'hsr_admin:delete_reservation' reservation.id %}"
            class="block p-4 py-2 rounded-md bg-red-500 hover:bg-red-700">Delete</a> -->
        </td>
      </tr>

      {% endfor %}
    </tbody>
  </table>
</div>

<script>

</script>

{% endblock body %}

hsr_admin/templates/hsr_admin/view_reservation.html
{% extends 'hsr_admin/base.html' %}


{% block body %}
<div class=" overflow-x-hidden">
    <div class="p-6 ">
      <h2 class="text-2xl mb-4 text-white">Reservation Details</h2>
      <p class="mb-2 text-white">Reservation ID: {{ reservation.code }}</p>
      <p class="mb-2 text-white">Arrival Date: {{ reservation.arrival_date }}</p>
      <p class="mb-2 text-white">Departure Date: {{ reservation.departure_date }}</p>
      
      <hr class="my-6 border-white">
      
      <h2 class="text-2xl mb-4 text-white">Customer Details</h2>
      <p class="mb-2 text-white">First Name: {{ reservation.customer.first_name }}</p>
      <p class="mb-2 text-white">Last Name: {{ reservation.customer.last_name }}</p>
      <p class="mb-2 text-white">Email Address: {{ reservation.customer.email_address }}</p>
      <p class="mb-2 text-white">Phone Number: {{ reservation.customer.phone_number }}</p>
      <p class="mb-2 text-white">Identification Type: {{ reservation.customer.id_type }}</p>

      <p class="mb-2 text-white">Identification Number: {{ reservation.customer.id_number }}</p>

      
      <hr class="my-6 border-white">
      
      <h2 class="text-2xl mb-4 text-white">Room Details</h2>
      <p class="mb-2 text-white">Category: {{ reservation.room.category.title }}</p>
      <p class="mb-2 text-white">Room Number: {{ reservation.room.number }}</p>
      <p class="mb-2 text-white">Room Title: {{ reservation.room.title }}</p>
      <p class="mb-2 text-white">Room Price: N{{ reservation.room.category.price }}</p>
    </div>
  </div>
  
  <div class="mt-4 flex justify-start p-6">
    <!-- <a href="{% url 'hsr_admin:view_reservation' reservation.id %}" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700">Edit Reservation</a> -->
    <form action="{% url 'hsr_admin:delete_reservation' reservation.id %}" method="POST" class="ml-2 inline-block">
      {% csrf_token %}
      <button type="submit" class="px-4 py-2 bg-red-500 text-white rounded hover:bg-red-700">Delete Reservation</button>
    </form>
  </div>
  
  
{% endblock body %}
    

hsr_admin/templates/hsr_admin/view_room.html
{% extends 'hsr_admin/base.html' %}


{% block title  %}
    Rooms Reservations
{% endblock title  %}


{% block body %}
<form action="" method="post">
    {% csrf_token %}
    <div class="w-full text-center mt-6 text-lg">
        <span class="text-red-600">{{error}}</span>
        <span class="text-green-600">{{success}}</span>
    </div>
    <div class="px-6 lg:px-16 flex flex-col space-y-8">
        <div class="flex flex-col lg:flex-row justify-center lg:space-x-4 my-4">
            <div class="flex flex-col w-full">
                <label class="pt-8 mb-2 block" for="">Room Number</label>
                <input
                    class="bg-transparent border-white w-full shadow-md px-8 py-4 outline-none border-2 border-black/40 rounded-md hover:border-indigo-600"
                     name="room_number" value="{{room.number}}" />
            </div>

            <div class="flex flex-col w-full">
                <label class="pt-8 mb-2 block" for="">Room Category</label>
                <select
                    class="bg-transparent border-white w-full shadow-md px-8 py-4 outline-none border-2 border-black/40 rounded-md hover:border-indigo-600"
                    name="category" value="room.category.pk" id="">

                    {% for category in categories %}
                    <option value="{{category.pk}}">{{category}}</option>
                    {% endfor %}

                </select>
            </div>
        </div>

        <div class="flex flex-col">
            <label class="pt-8 mb-2 block" for="">Room Description</label>
                
            <textarea
            class="bg-transparent border-white w-full shadow-md px-8 py-4 outline-none border-2 border-black/40 rounded-md hover:border-indigo-600"
            name="description">
        {{room.description}}
    </textarea>
        </div>

        <div class="mb-6 block">
            <button class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded">
                Update Room
            </button>
        </div>
    </div>
</form>

<div class="p-6 lg:px-16">
    <span class="block my-6 text-2xl">Room Reservations</span>
    <table class="min-w-full">
        <thead class="">
            <tr class="py-8">
                <th class="py-4 px-4  text-left">ID</th>
                <th class="py-4 px-4  text-left">Arrival Date</th>
                <th class="py-4 px-4  text-left">Departure Date</th>
                <th class="py-4 px-4  text-left">Customer</th>
                <th class="py-4 px-4  text-left">Paid</th>


                <th class="py-4 px-4  text-left">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for reservation in reservations %}
            <tr>
                <td class="py-2 px-4  text-left">{{ reservation.id }}</td>
                <td class="py-2 px-4  text-left">{{ reservation.arrival_date }}</td>
                <td class="py-2 px-4  text-left">{{ reservation.departure_date }}</td>
                <td class="py-2 px-4  text-left">{{ reservation.customer.first_name }} {{ reservation.customer.last_name}}</td>
                <td class="py-2 px-4  text-left">

                    {% if reservation.paid %}
                    <span class="text-green-600">paid</span>
                    {% else %}
                    <span>not paid</span>
                    {% endif %}

                </td>

                <td class="py-2 px-4  text-left">
                    <a href="{% url 'hsr_admin:view_reservation' reservation.id %}"
                        class="text-blue-500 hover:text-blue-700 mr-2">View</a>
                    <a href="" class="text-yellow-500 hover:text-yellow-700 mr-2">Edit</a>
                    <a href="{% url 'hsr_admin:delete_reservation' reservation.id %}"
                        class="text-red-500 hover:text-red-700">Delete</a>
                </td>
            </tr>
                
            {% endfor %}
        </tbody>
    </table>
</div>


    
{% endblock body %}
    